zDeath-Radio:
  spawnLimit: 10000
  chanceOfInfection: 12
  breakableBlocks:
   - DIRT
   - GRASS
   - GRASS_BLOCK
   - OAK_TRAPDOOR
   - ACACIA_TRAPDOOR
   - BIRCH_TRAPDOOR
   - JUNGLE_TRAPDOOR
   - CHEST
   - COBBLESTONE
   - OAK_PLANKS
   - ACACIA_PLANKS
   - BIRCH_PLANKS
   - JUNGLE_PLANKS
   - SPRUCE_PLANKS
   - DARK_OAK_PLANKS
   - MANGROVE_PLANKS
   - CRIMNSON_PLANKS
   - WARPED_PLANKS