name: zDeath-Radio
version: 0.0.5
main: com.nullpointercoding.zdeathradio.Main
api-version: 1.13
authors: [xxCoderforlife]
load: POSTWORLD
#COMMANDS
commands:
  zdeathradio:
    permission: 
    description: Root Command For zDeath-Radio
    usage: /zdeathradio
    aliases: [ zdr ]
permissions:
  zdeathradio.admin:
    description: Allows access to all zDeath-Radio commands
    default: op